import { precacheAndRoute } from 'workbox-precaching'

// Precache all assets generated by the build
precacheAndRoute(self.__WB_MANIFEST)

// Push notification handler
self.addEventListener('push', (event) => {
  const data = event.data?.json() || {}
  const title = data.title || 'JOSSFITness'
  const options = {
    body: data.body || '',
    icon: '/icon-192x192.png',
    badge: '/icon-96x96.png',
    data: { url: data.url || '/' },
  }
  event.waitUntil(self.registration.showNotification(title, options))
})

// Notification click handler
self.addEventListener('notificationclick', (event) => {
  event.notification.close()
  const url = event.notification.data?.url || '/'
  event.waitUntil(clients.openWindow(url))
})
