import { precacheAndRoute } from 'workbox-precaching'

// Precache all assets generated by the build
precacheAndRoute(self.__WB_MANIFEST)

// ─── Rest Timer Background Notification ───
let restTimerTimeout = null

self.addEventListener('message', (event) => {
  const { type, remainingMs } = event.data || {}

  if (type === 'REST_TIMER_START') {
    // Clear any existing scheduled notification
    if (restTimerTimeout) clearTimeout(restTimerTimeout)

    restTimerTimeout = setTimeout(() => {
      self.registration.showNotification('JOSSFITness', {
        body: '¡Descanso terminado! Hora de la siguiente serie 💪',
        icon: '/icon-192x192.png',
        badge: '/icon-96x96.png',
        tag: 'rest-timer',
        renotify: true,
        vibrate: [200, 100, 200, 100, 200],
        data: { url: '/' },
      })
      restTimerTimeout = null
    }, remainingMs)
  }

  if (type === 'REST_TIMER_CANCEL') {
    if (restTimerTimeout) {
      clearTimeout(restTimerTimeout)
      restTimerTimeout = null
    }
  }
})

// Push notification handler
self.addEventListener('push', (event) => {
  const data = event.data?.json() || {}
  const title = data.title || 'JOSSFITness'
  const options = {
    body: data.body || '',
    icon: '/icon-192x192.png',
    badge: '/icon-96x96.png',
    data: { url: data.url || '/' },
  }
  event.waitUntil(self.registration.showNotification(title, options))
})

// Notification click handler
self.addEventListener('notificationclick', (event) => {
  event.notification.close()
  const url = event.notification.data?.url || '/'
  // Focus existing window or open new one
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      for (const client of windowClients) {
        if (client.url.includes(self.location.origin) && 'focus' in client) {
          return client.focus()
        }
      }
      return clients.openWindow(url)
    })
  )
})
